### ISSUE TITLE
speexenc encode wav file dos vulnerability

### ISSUE THREAD

**Issue by Aurorainfinity** [xiph/speex#13]
when speexenc encode wav file , deal with channels 0 will generate a Division by zero error which will cause the software crash
[sample.tar.gz](https://github.com/xiph/speex/files/4910664/sample.tar.gz)
usage :
    speexenc sample -

vulnerability function:
static int read_samples(FILE *fin,int frame_size, int bits, int channels, int lsb, short * input, char *buff, spx_int32_t *size)
{
   unsigned char in[MAX_FRAME_BYTES*2];
   int i;
   short *s;
   int nb_read;
   size_t to_read;

   if (size && *size<=0)
   {
      return 0;
   }

   to_read = bits/8*channels*frame_size;

**Comment by tmatth** [comment]
@Aurorainfinity thanks, there's a fix waiting for review here if you want to test it out:
https://gitlab.xiph.org/xiph/speex/-/merge_requests/1

FYI: We only use github as a mirror, that's why the MR is over on our gitlab instance.

**Comment by tmatth** [comment]
Just to clarify, the code in question is **not part of the libspeex library**, it's only part of the the `speexenc` example program.
