### ISSUE TITLE
Hi,Is the speex component being maintained? 

### ISSUE THREAD

**Issue by FWT-Henry** [xiph/speex#15]
Hi,
Is the speex component being maintained? It seems like it hasn't been updated for a long time.
^_^

**Comment by tmatth** [comment]
@FWT-Henry yes, discussion + development happens on http://lists.xiph.org/mailman/listinfo/speex-dev. Lately the focus has been on fuzzing the speex decoder.

**Comment by tmatth** [comment]
@FWT-Henry although this github mirror seems to be out of date, official upstream lives here:
https://gitlab.xiph.org/xiph/speex
