### ISSUE TITLE
Veracode scan complains the calloc is not checked for return value

### ISSUE THREAD

**Issue by KrishnaRLolage** [xiph/speex#18]
We use [Veracode](https://web.analysiscenter.veracode.com/) for scanning our mobile application. It complains the following when this library is used in my code.

The result of this call to calloc() is not checked for success before being used. This can result in application instability or crashing if memory is not available.

Can this be fixed?

https://github.com/xiph/speex/blob/870ff845b32f314aec0036641ffe18aba4916887/libspeex/os_support.h#L56

**Comment by ePirat** [comment]
In the mentioned line there is nothing to fix, the function is essentially a wrapper for `calloc` so there is nothing to handle there.

So this sounds like a false positive find.

**Comment by KrishnaRLolage** [comment]
But wherever this wrapper is called, the return type is not always checked for return value.
For e.g at line 124 in speex_header.c file

https://github.com/xiph/speex/blob/870ff845b32f314aec0036641ffe18aba4916887/libspeex/speex_header.c#L124

**Comment by ePirat** [comment]
Then you should report us these cases instead, not the wrapper, as thats not helpful. If you have a list of all cases where the return is not checked, please let us know.

**Comment by KrishnaRLolage** [comment]
I do not have a specific list, a grep search would help.
