### ISSUE TITLE
Difficulty in compiling

### ISSUE THREAD

**Issue by hc1230** [xiph/speex#19]
So i wrote a test.c to verify the encoding function. I used 'stdio.h' and 'speex.h' as header files. After i type "gcc -o test test.c",it displays errors like "undefined reference to 'speex_encoder_init' "(and other functions such as speex_encode, speex_bits_reset). I guess there is something wrong with my cammand line,but i really don't know how to fix it.

**Comment by tmatth** [comment]
> So i wrote a test.c to verify the encoding function. I used 'stdio.h' and 'speex.h' as header files. After i type "gcc -o test test.c",it displays errors like "undefined reference to 'speex_encoder_init' "(and other functions such as speex_encode, speex_bits_reset). I guess there is something wrong with my cammand line,but i really don't know how to fix it.

You need to build the actual speex library and link against it, the simplest way is to install it:
https://gitlab.xiph.org/xiph/speex/-/blob/master/INSTALL

Feel free to ask for help on #speex or #xiph on https://libera.chat/ but closing as this isn't a bug in speex.
