### ISSUE TITLE
Undefined behavior / Arithmetic overflow in bits.c

### ISSUE THREAD

**Issue by Dutchman101** [xiph/speex#25]
`libspeex\bits.c(278): warning C26453: Arithmetic overflow: Left shift of a negative signed number is undefined behavior (io.4)`

@ [libspeex/bits.c Line 278](https://github.com/xiph/speex/blob/be6df4d61427c04b6609205fab079a1e6a05cb69/libspeex/bits.c#L278)

**Comment by Dutchman101** [comment]
Hey @tmatth .. is this a maintained repo? I thought you guys were spotting activity here, to carry and file it over at gitlab.

**Comment by tmatth** [comment]
> Hey @tmatth & @orbea .. is this a maintained repo? I thought you guys were spotting activity here, to carry and file it over at gitlab. I've made a fix at PR #26, ez merge.
> 
> If you see this comment, please also look at #27 (that's not pretty either) and perhaps my [PR in speexdsp repo](https://github.com/xiph/speexdsp/pull/50).

Yeah so as you said, this is just a mirror of the official upstream at https://gitlab.xiph.org/xiph/speexdsp (but we do port patches etc. over)

That said thanks for pinging I will check these ASAP.

**Comment by tmatth** [comment]
Applied in https://gitlab.xiph.org/xiph/speex/-/commit/aca6801183bad01458140dbbab71a68a02e5a561
