### ISSUE TITLE
speexenc hangs on corrupted input file

### ISSUE THREAD

**Issue by tianxiaogu** [xiph/speex#9]
Our fuzzing tool has found an input that makes `speexenc` hang on it. Attached is the corrupted input.

[32.zip](https://github.com/xiph/speex/files/2369525/32.zip)

```
speexenc  32 -
```

**Comment by tmatth** [comment]
@tianxiaogu nice catch, do you want to try https://github.com/xiph/speex/pull/10 ?

**Comment by tianxiaogu** [comment]
@tmatth

**Comment by tianxiaogu** [comment]
@tmatth , Thanks very much for your reply. We have run the fuzzer for hours. And this is the only issue we have found. speex is really reliable. We will improve our fuzzer and keep fuzzing on speex.

**Comment by tmatth** [comment]
@tianxiaogu great, let me know if you find others.

**Comment by tmatth** [comment]
Fixed in bdc392257c330e49872a5217dfb56becd1ee8f45
